core/urls.py
from django.urls import path
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^search/$', views.search, name='search'),
    path('product/<int:product_id>', views.product, name='product'),
    path('substitute/<int:product_id>', views.substitute, name='substitute'),
    path('save/<int:product_id>/<int:prod_id>', views.save, name='save'),
    path('favorite/', views.favorite, name='favorite'),
    path('delete/<int:fav>', views.delete, name='delete'),
]

app_name = 'core'

purbeurre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('legal', views.legal, name='legal'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('core/', include('core.urls')),
]

handler404 = views.my_404_view
handler500 = views.my_500_view

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = (
    path('register', views.register, name='register'),
    path('login', views.LoginFormView.as_view(
        template_name='login.html'), name='login'),
    path('logout', views.logout_view, name='logout'),
    path('profile', views.profile, name='profile'),
    path('delete_account', views.delete_account, name='delete_account'),
)

app_name = 'users'

purbeurre/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

def legal(request):
    return render(request, 'legal.html')

def my_404_view(request, exception):
    """ Error 404 page """
    return render(request, '404.html')


def my_500_view(request):
    """ Error 500 page """
    return render(request, '500.html')

templates/purbeurre/base.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        {% load static %}
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Pure Beurre | {% block title %}{% endblock %}</title>
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'css/style.css' %}" rel="stylesheet" />
        <!-- Favicon-->
        <link rel="icon" href="{% static 'img/logo_pur_beurre-favicon.ico' %}" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        {% include 'nav.html' %}
        <!-- Content-->
        {% block content %}{% endblock %}
        <!-- Footer-->
        <footer class="py-3">
            <div class="container">
                <div class="row text-center text-muted">
                    <div class="col-6 text-center"><a href="{% url 'legal' %}">Mentions légales</a></div>
                    <div class="col-6 text-center"><a href="{% url 'index' %}#contact">Contact</a></div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/purbeurre/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Accueil{% endblock %}
{% block content %}
<!-- Masthead-->
<header class="masthead">
    {% if messages %}
        {% for message in messages %}
            <div class="row justify-content-center">
                <div class="position-absolute text-center alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    <div class="container h-100 mt-5">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">Du gras, oui, mais de qualité !</h1>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-8 align-self-baseline">
                <h2 class="text-white font-weight-light mb-5">Trouvez un produit de substitution
                    pour ceux que vous consommez tous les jours</h2>
                <form class="input-group" action="{% url 'core:search' %}" method="get">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Produit" name="query">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Rechercher</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</header>
<!-- Services-->
<section class="page-section" id="services">
    <div class="container">
        <h2 class="text-center mt-0">Colette et Rémy</h2>
        <hr class="divider my-4" />
        <p><strong>Pur Beurre</strong> est l'initiative de deux amoureux de la gastronomie française, Colette Tatou et Rémy, que vous avez déjà certainement rencontrés dans notre excellent restaurant Ratatouille. </p>
        <p><strong>Colette Tatou</strong> : "Nous aimons tous manger, surtout en France ! Personnellement, une baguette fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement. Comme tout le monde, je fais mes courses au supermarché. Mais petit à petit je me suis rendue compte, surtout lorsque nous avons ouvert le restaurant, que je pouvais remplacer les produits aseptisés que j'avais l'habitude d'acheter par de bons produits du terroir Et souvent pour le même prix !"</p>
        <p><strong>Remy</strong> : "Pour ma part je me rendais déjà dans bien des magasins car j'aime beaucoup me balader, surtout dans les caves et les cuisines. Je connaissais par coeur le contenu des boutiques bio (dont je raffole) ainsi que les ingrédients de tous les aliments vendus. Lorsque Colette m'a demandé si elle pouvait remplacer son Nutella matinal par un aliment plus sain, je savais tout de suite où le trouver. L'idée de Pur Beurre était née !"</p>
        <div class="row">
            <div class="col-md-6 text-center">
                <div class="mt-5">
                    <img class="portrait" src="{% static 'img/colette-tatou-full.png' %}" alt="Colette Tatou">
                    <h3 class="h4 my-2">Colette</h3>
                </div>
            </div>
            <div class="col-md-6 text-center">
                <div class="mt-5">
                    <img class="portrait" src="{% static 'img/ratatouille-portrait.jpg' %}" alt="Rémy">
                    <h3 class="h4 my-2">Rémy</h3>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Contact-->
<section class="page-section" id="contact">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="mt-0">Contactez-nous!</h2>
                <hr class="divider my-4" />
                <p class="text-muted mb-5">Nous vous répondrons le plus vite possible!</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 ml-auto text-center mb-5 mb-lg-0">
                <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
                <div>+594 0594 123456</div>
            </div>
            <div class="col-md-4 mr-auto text-center">
                <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                <a class="d-block" href="mailto:contact@yourwebsite.com">contact@purbeurre.com</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/purbeurre/legal.html
{% extends 'purbeurre/base.html' %}
{% load static %}
{% block title %}Mentions légales{% endblock %}
{% block content %}
    <section class="page-section" id="kotyk">
        <div class="container">
            <div class="row justify-content-center">
                <h2 class="bg-secondary mb-5 p-2 text-light rounded">Mentions légales</h2>
            </div>
        </div>
    </section>
    <section class="page-section">
        <div class="container">
            <div class="justify-content-center">
                <h2 class="col text-center text-dark">Ce site est hébergé sur <a class="text-decoration-none" target="_blank" href="https://www.heroku.com">Heroku</a> et utilise les ressources suivantes:</h2>
            </div>
            <div class="row justify-content-center mt-5">
                <div class="mb-5 col-md-4 mb-lg-0 text-center">
                    <div class="bg-transparent text-dark">
                        <img src="{% static 'img/kawin-harasai.jpg' %}" class="img-fluid legal" alt="Photo de kawin harasai">
                        <div class="card-body">
                            <h5 class="card-title">Kawin Harasai</h5>
                            <p class="card-text">Image de fond</p>
                            <a target="_blank" href="https://unsplash.com/photos/k60JspcBwKE" class="btn btn-primary">Lien vers Unsplash</a>
                        </div>
                    </div>
                </div>
                <div class="mb-5 col-md-4 mb-lg-0 text-center">
                    <div class="bg-transparent text-dark">
                        <img src="{% static 'img/greg-jeanneau.jpg' %}" class="img-fluid legal" alt="Photo de Greg Jeanneau">
                        <div class="card-body">
                            <h5 class="card-title">Greg Jeanneau</h5>
                            <p class="card-text">Image de fond</p>
                            <a target="_blank" href="https://unsplash.com/photos/YTbFHT9_IhY" class="btn btn-primary">Lien vers Unsplash</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 text-center">
                    <div class="bg-transparent text-dark">
                        <img src="{% static 'img/olenka-kotyk.jpg' %}" class="img-fluid legal" alt="Photo de Olenka Kotyk">
                        <div class="card-body">
                            <h5 class="card-title">Olenka Kotyk</h5>
                            <p class="card-text">Image de fond</p>
                            <a target="_blank" href="https://unsplash.com/photos/eqsEZNCm4-c" class="btn btn-primary">Lien vers Unsplash</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="mb-5 col-md-4 mb-lg-0 text-center">
                    <div class="bg-transparent text-dark">
                        <img src="{% static 'img/carrot.png' %}" class="img-fluid legal bg-light" alt="Icône de carotte">
                        <div class="card-body">
                            <h5 class="card-title">Fabien Jouin</h5>
                            <p class="card-text">Icône de carotte</p>
                            <a target="_blank" href="https://thenounproject.com/FabienJ/" class="btn btn-primary">Lien vers thenounproject.com</a>
                        </div>
                    </div>
                </div>
                <div class="mb-5 col-md-4 mb-lg-0 text-center">
                    <div class="bg-transparent text-dark">
                        <img src="{% static 'img/openfoodfacts.png' %}" class="img-fluid legal bg-light" alt="Photo de OpenFoodFatcs">
                        <div class="card-body">
                            <h5 class="card-title">OpenFoodFacts</h5>
                            <p class="card-text">Base de données</p>
                            <a target="_blank" href="https://fr.openfoodfacts.org/" class="btn btn-primary">Lien vers OpenFoodFacts</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 text-center">
                    <div class="bg-transparent text-dark">
                        <img src="{% static 'img/bootstrap.jpg' %}" class="img-fluid legal" alt="Photo du theme de Bootstrap">
                        <div class="card-body">
                            <h5 class="card-title">Bootstrap</h5>
                            <p class="card-text">Theme de Bootstrap</p>
                            <a target="_blank" href="https://startbootstrap.com/themes/creative/" class="btn btn-primary">Lien vers Bootstrap creative</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="justify-content-center mt-5">
            <h2 class="col text-center text-dark">Code source sur <a class="text-decoration-none" target="_blank" href="https://github.com/MikaIce/PlateForm_Nut_P08">Github</a></h2>
            <h6 class="col text-center text-dark mt-3">Create By Michael BENOIT 2022</h6>
        </div>
    </section>
{% endblock %}

templates/purbeurre/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'index' %}">
            <img class="logo_pur_beurre" src="{% static 'img/logo_pur_beurre.png' %}"
                 alt="logo pur beurre">
            Pur Beurre</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto my-2 my-lg-0">
                <li class="nav-item">
                    <form class="input-group mt-2" action="{% url 'core:search' %}" method="get">
                        <input type="text" class="form-control" placeholder="Chercher" name="query">
                    </form>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item mt-3"><a class="nav-link js-scroll-trigger" href="{% url 'users:profile' %}">
                        <i class="fas fa-user fa-2x ml-2" title="Mon profil"></i>
                    </a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'core:favorite' %}" title="Mes favoris">
                        {% include 'carrot.svg' %}
                    </a></li>
                    <li class="nav-item mt-3"><a class="nav-link js-scroll-trigger" href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt fa-2x ml-2" title="Se déconnecter"></i>
                    </a></li>
                {% else %}
                    <li class="nav-item mt-3"><a class="nav-link js-scroll-trigger" href="{% url 'users:register' %}">
                        <i class="fas fa-user-plus fa-2x ml-2" title="Créer un compte"></i>
                    </a></li>
                    <li class="nav-item mt-3"><a class="nav-link js-scroll-trigger" href="{% url 'users:login' %}">
                        <i class="fas fa-sign-in-alt fa-2x ml-2" title="Se connecter"></i>
                    </a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>