core/urls.py
from django.urls import path
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^search/$', views.search, name='search'),
    path('product/<int:product_id>', views.product, name='product'),
    path('substitute/<int:product_id>', views.substitute, name='substitute'),
    path('save/<int:product_id>/<int:prod_id>', views.save, name='save'),
    path('favorite/', views.favorite, name='favorite'),
    path('delete/<int:fav>', views.delete, name='delete'),
]

app_name = 'core'

purbeurre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('legal', views.legal, name='legal'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('core/', include('core.urls')),
]

handler404 = views.my_404_view
handler500 = views.my_500_view

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    name = models.CharField(verbose_name="Nom du produit",
                            max_length=100, unique=True)
    brands = models.CharField(verbose_name="Marques du produit",
                              max_length=100)
    link = models.URLField(unique=True)
    nutriscore = models.CharField(max_length=1)
    image = models.URLField()
    fat = models.FloatField()
    saturated_fat = models.FloatField()
    sugars = models.FloatField()
    salt = models.FloatField()

    class Meta:
        verbose_name = 'Produit'
        verbose_name_plural = "Produits"
        ordering = ['name']

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    products = models.ManyToManyField(Product, related_name='categories')

    class Meta:
        verbose_name = 'Catégorie'
        verbose_name_plural = "Catégories"
        ordering = ['name']

    def __str__(self):
        return self.name

class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='users')
    sub = models.ForeignKey(Product, on_delete=models.CASCADE,
                            related_name='subs')
    prod = models.ForeignKey(Product, on_delete=models.CASCADE,
                             related_name='prods')

    def __str__(self):
        return str(self.sub) + " remplace : " + str(self.prod) \
               + " sauvegardé par : " \
               + str(self.user)

    class Meta:
        verbose_name = "Favori"
        verbose_name_plural = "Favoris"
        ordering = ['user']

core/views.py
import logging
from django.shortcuts import render, redirect
from .models import Product, Favorite
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required

logger = logging.getLogger(__name__)

def paginate(request, args, prods_per_page):
    """ Paginate function """
    paginator = Paginator(args, prods_per_page)
    page_number = request.GET.get('page', 1)

    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    return page_obj

def search(request):
    """ Display product or products matching the user's request """
    query = request.GET.get('query')
    if query:
        # search by product name
        products = Product.objects.filter(
            name__icontains=query).order_by('nutriscore', 'id')

        # if nothing is found, search by brands name
        if not products.exists():
            products = Product.objects.filter(
                brands__icontains=query).order_by('nutriscore', 'id')
        # if nothing is found
        if not products.exists():
            messages.success(request,
                             "Nous n'avons trouvé aucun produit "
                             "correspondant à votre recherche")
            return redirect('index')

        context = {'page_obj': paginate(request, products, 9),
                   'query': query}

        logger.info('New search', exc_info=True, extra={
            # Optionally pass a request and we'll grab any information we can
            'request': request,
        })

        return render(request, 'core/search.html', context)

    else:
        messages.success(request, "Vous n'avez rien saisi")
        return redirect('index')

def product(request, product_id):
    """ Display the product's information """
    prod = Product.objects.get(id=product_id)
    context = {'prod': prod}
    return render(request, 'core/product.html', context)


def substitute(request, product_id):
    """ Display substitutes list """
    prod = Product.objects.get(id=product_id)
    cat = prod.categories.get()
    subs = cat.products.all().order_by('nutriscore', 'id')
    sub_list = []
    for i in subs:
        if i.nutriscore <= prod.nutriscore:
            sub_list.append(i)

    sub_list.remove(prod)
    context = {'prod': prod,
               'page_obj': paginate(request, sub_list, 9)}
    return render(request, 'substitute.html', context)

@login_required
def save(request, product_id, prod_id):
    """ Saves product and substitute """
    user = request.user
    try:
        fav = Favorite.objects.filter(user_id=user.id,
                                      sub_id=product_id,
                                      prod_id=prod_id)
        if not fav:
            Favorite.objects.create(user_id=user.id,
                                    sub_id=product_id,
                                    prod_id=prod_id)
            messages.success(request, 'Produit sauvegardé')
        else:
            messages.success(request, 'Le produit est déjà sauvegardé')

    finally:
        return redirect('index')


@login_required
def favorite(request):
    """ Display user's favorites """
    user = request.user
    favs = Favorite.objects.filter(user_id=user.id)

    context = {'page_obj': paginate(request, favs, 3)}
    return render(request, 'favorite.html', context)


@login_required
def delete(request, fav):
    """ Delete user's favorite """
    favori = Favorite.objects.filter(id=fav)
    favori.delete()
    messages.success(request, 'Le favori à bien été supprimé')
    return redirect('index')

templates/core/favorite.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Mes produits{% endblock %}
{% block content %}
    <section id="jeanneau" class="h-50">
        <div class="container">
            <div class="row justify-content-center mt-5">
                <h2 class="bg-secondary text-light p-2 rounded">Mes produits</h2>
            </div>
        </div>
    </section>
{% if page_obj %}
    <section class="h-auto">
        <div class="container">
            <div class="row mt-5">
                    {% for fav in page_obj %}
                        <div class="col-md-4 col-xs-12 my-5">
                            <div class="card border-primary">
                                <div class="nutriscore nutriscore-{{ fav.sub.nutriscore }} text-center">
                                    {{ fav.sub.nutriscore|upper }}
                                </div>
                                <a class="mx-auto" title="Voir la fiche de ce produit" href="{% url 'core:product' product_id=fav.sub.id %}">
                                    <img src="{{ fav.sub.image }}" class="image_url img-fluid mt-3 mx-auto" alt="Photo du produit">
                                </a>
                                <div id="card" class="card-body">
                                    <h5 class="card-title short" title="{{ fav.sub.name }}">{{ fav.sub.name }}</h5>
                                    <p class="card-text short" title="{{ fav.sub.brands }}">Marque: {{ fav.sub.brands }}</p>
                                    <a href="{% url 'core:substitute' product_id=fav.sub.id %}" class="btn btn-primary d-block w-75 mx-auto">
                                        Rechercher un substitut
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 my-auto">
                            <h2 class="text-center mb-5">Remplace</h2>
                            <a href="{% url 'core:delete' fav=fav.id %}" class="btn btn-danger d-block w-50 mx-auto">
                                Supprimer ce favori
                            </a>
                        </div>
                        <div class="col-md-4 my-5">
                            <div class="card border-primary">
                                <div class="nutriscore nutriscore-{{ fav.prod.nutriscore }} text-center">
                                    {{ fav.prod.nutriscore|upper }}
                                </div>
                                <a class="mx-auto" title="Voir la fiche de ce produit" href="{% url 'core:product' product_id=fav.prod.id %}">
                                    <img src="{{ fav.prod.image }}" class="image_url img-fluid mt-3 mx-auto" alt="Photo du produit">
                                </a>
                                <div class="card-body">
                                    <h5 class="card-title short" title="{{ fav.prod.name }}">{{ fav.prod.name }}</h5>
                                    <p class="card-text short" title="{{ fav.prod.brands }}">Marque: {{ fav.prod.brands }}</p>
                                    <a href="{% url 'core:substitute' product_id=fav.prod.id %}" class="btn btn-primary d-block w-75 mx-auto">
                                        Rechercher un substitut
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                <div class="container pagination justify-content-center mb-5">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; Début</a>
                            <a href="?page={{ page_obj.previous_page_number }}">Page précédente</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">Page suivante</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">Fin &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </section>
{% else %}
    <section class="h-75 mt-5">
        <div class="container" style="height: 230px;">
            <div class="row">
                <div class="col">
                    <h2 class="text-center">Vous n'avez actuellement aucun favori</h2>
                </div>
            </div>
        </div>
    </section>
{% endif %}
{% endblock %}

templates/core/product.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ prod.name }}{% endblock %}
{% block content %}
    <section id="prod" class="h-50 py-5" style="background-image: url({{ prod.image }})">
        <div class="container">
            <div class="row justify-content-center text-light mt-5">
                <h2 class="bg-secondary text-center p-2 rounded mt-5">{{ prod.name }}</h2>
            </div>
        </div>
    </section>
    <section class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-lg-6">
                <img src="https://static.openfoodfacts.org/images/misc/nutriscore-{{prod.nutriscore}}.png" alt="NutriScore">
            </div>
            <div class="col-lg-6">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Repères nutritionnels</th>
                            <th scope="col">pour 100g</th>
                        </tr>
                    </thead>
                    <tbody class="text-muted">
                        <tr>
                            <th scope="row">Matières grasses</th>
                            <td>{{ prod.fat }}g</td>
                        </tr>
                        <tr>
                            <th scope="row">Matières grasses saturées</th>
                            <td>{{ prod.saturated_fat }}g</td>
                        </tr>
                        <tr>
                            <th scope="row">Sucre</th>
                            <td>{{ prod.sugars }}g</td>
                        </tr>
                        <tr>
                            <th scope="row">Sel</th>
                            <td>{{ prod.salt }}g</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row justify-content-center my-5">
            <a target="_blank" class="btn btn-primary" href="{{ prod.link }}" role="button">Voir la fiche d'OpenFoodFacts</a>
        </div>
    </section>
{% endblock %}

templates/core/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Recherche{% endblock %}
{% block content %}
    <section id="jeanneau" class="h-50">
        <div class="container">
            <div class="row justify-content-center mt-5">
                <h3 class="bg-secondary text-light text-center p-2 rounded">Voici les produits correspondants à votre recherche</h3>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row mt-5">
                {% for product in page_obj %}
                    <div class="col-md-4 my-5">
                        <div class="card border-primary">
                            <div class="nutriscore nutriscore-{{ product.nutriscore }} text-center">
                                {{ product.nutriscore|upper }}
                            </div>
                            <a class="mx-auto" title="Voir la fiche de ce produit" href="{% url 'core:product' product_id=product.id %}">
                                <img src="{{ product.image }}" class="image_url img-fluid mt-3 mx-auto" alt="Photo du produit">
                            </a>
                            <div id="card" class="card-body">
                                <h5 class="card-title short" title="{{ product.name }}">{{ product.name }}</h5>
                                <p class="card-text short" title="{{ product.brands }}">Marque: {{ product.brands }}</p>
                                <a href="{% url 'core:substitute' product_id=product.id %}" class="btn btn-primary d-block w-75 mx-auto">
                                    Rechercher un substitut
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="container pagination justify-content-center mb-5">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?query={{ query }}&page=1">&laquo; Début</a>
                        <a href="?query={{ query }}&page={{ page_obj.previous_page_number }}">Page précédente</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?query={{ query }}&page={{ page_obj.next_page_number }}">Page suivante</a>
                        <a href="?query={{ query }}&page={{ page_obj.paginator.num_pages }}">Fin &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </section>
{% endblock %}

templates/core/substitute.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Substituts{% endblock %}
{% block content %}
    <section id="prod" class="h-50 py-5" style="background-image: url({{ prod.image }})">
        <div class="container">
            <div class="row justify-content-center text-light mt-5">
                <h2 class="bg-secondary p-2 text-center rounded mt-5">{{ prod.name }}</h2>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row mt-5">
                {% for sub in page_obj %}
                    <div class="col-md-4 my-5">
                        <div class="card border-primary">
                            <div class="nutriscore nutriscore-{{ sub.nutriscore }} text-center">
                                {{ sub.nutriscore|upper }}
                            </div>
                            <a class="mx-auto" title="Voir la fiche de ce produit" href="{% url 'core:product' product_id=sub.id %}">
                                <img src="{{ sub.image }}" class="image_url img-fluid mt-3 mx-auto" alt="Photo du produit">
                            </a>
                            <div id="card" class="card-body">
                                <h5 class="card-title short" title="{{ sub.name }}">{{ sub.name }}</h5>
                                <p class="card-text short" title="{{ sub.brands }}">Marque: {{ sub.brands }}</p>
                                {% if user.is_authenticated %}
                                    <a href="{% url 'core:save' product_id=sub.id prod_id=prod.id %}" class="btn btn-primary d-block w-50 mx-auto">
                                        <i class="fas fa-save mr-2"></i>Sauvegarder
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="pagination justify-content-center mb-5">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; Début</a>
                        <a href="?page={{ page_obj.previous_page_number }}">Page précédente</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">Page suivante</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">Fin &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </section>
{% endblock %}