core/urls.py
from django.urls import path
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^search/$', views.search, name='search'),
    path('product/<int:product_id>', views.product, name='product'),
    path('substitute/<int:product_id>', views.substitute, name='substitute'),
    path('save/<int:product_id>/<int:prod_id>', views.save, name='save'),
    path('favorite/', views.favorite, name='favorite'),
    path('delete/<int:fav>', views.delete, name='delete'),
]

app_name = 'core'

purbeurre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('legal', views.legal, name='legal'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('core/', include('core.urls')),
]

handler404 = views.my_404_view
handler500 = views.my_500_view

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = (
    path('register', views.register, name='register'),
    path('login', views.LoginFormView.as_view(
        template_name='login.html'), name='login'),
    path('logout', views.logout_view, name='logout'),
    path('profile', views.profile, name='profile'),
    path('delete_account', views.delete_account, name='delete_account'),
)

app_name = 'users'

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys
from pathlib import Path

class Profile(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='M')
    profile_image = models.ImageField(upload_to='profile_images/', blank=True)

    def save(self, *args, **kwargs):
        if not self.profile_image:
            if self.gender == 'F':
                self.profile_image = 'profile_images/default_female.jpg'
            else:
                self.profile_image = 'profile_images/default_male.jpg'
        else:
            img = Image.open(self.profile_image)
            if img.mode in ('RGBA', 'LA'):
                background = Image.new(img.mode[:-1], img.size, '#FFFFFF')
                background.paste(img, img.split()[-1])
                img = background

            if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)

            output = BytesIO()
            img.save(output, format='JPEG', quality=100)
            output.seek(0)
            self.profile_image = InMemoryUploadedFile(output, 'ImageField',
                "%s.jpg" % self.profile_image.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
        super().save(*args, **kwargs)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    gender = forms.ChoiceField(choices=Profile.GENDER_CHOICES)

    class Meta:
        model = User
        fields = ['username', 'email', 'gender', 'password1', 'password2']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_image']

users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, ProfileForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import LoginView
from .models import Profile


def register(request):
    """ User registration function """
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()

            # Check if the user already has a profile
            profile, created = Profile.objects.get_or_create(user=user)
            if not created:
                # If the profile already exists, update the gender
                profile.gender = form.cleaned_data.get('gender')
                profile.save()

            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            messages.success(request, 'Bienvenue! Votre compte a été créé avec succès. Vous êtes maintenant connecté.')
            login(request, user)
            return redirect('index')
        else:
            return render(request, 'register.html', {'form': form})
    else:
        form = RegisterForm()
        return render(request, 'register.html', {'form': form})


@login_required
def profile(request):
    """User update profile function"""
    if request.method == 'POST':
        p_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if p_form.is_valid():
            p_form.save()
            messages.success(request, 'Votre profil a été mis à jour avec succès!')
            return redirect('users:profile')
    else:
        p_form = ProfileForm(instance=request.user.profile)
    return render(request, 'profile.html', {'p_form': p_form})

class LoginFormView(SuccessMessageMixin, LoginView):
    """ Add a welcome message when user logs in """
    success_message = "Bienvenu! Vous êtes maintenant connecté"

@login_required
def logout_view(request):
    """ User logout function """
    logout(request)
    messages.success(request, 'Au revoir! Vous êtes maintenant déconnecté')
    return redirect('index')

@login_required
def delete_account(request):
    """User delete function"""
    profile = Profile.objects.get(user=request.user)
    profile.delete()
    request.user.delete()
    messages.success(request, 'Votre compte a été supprimé avec succès.')
    return redirect('index')

templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Se connecter{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <section id="harasai" class="h-100">
        <div class="container">
            <div class="row justify-content-center">
                <h2 class="bg-secondary p-2 rounded text-light mb-5">Se connecter</h2>
            </div>
            <div class="row justify-content-center">
                <form method="post" class="bg-light p-3 w-50 rounded">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary">Se connecter</button>
                    <p class="new mt-3">Nouveau ici? <a href="{% url 'users:register' %}">Créer un compte</a></p>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Mon profil{% endblock %}
{% block content %}
<section id="kotyk" class="h-75">
    <div class="container">
        <div class="row justify-content-center text-light mt-5">
            <h1 class="bg-secondary p-2 rounded">{{ user.username }}</h1>
        </div>
        <div class="row justify-content-center text-center">
            {% if user.profile.profile_image %}
                <img src="{{ user.profile.profile_image.url }}" alt="Profile picture" class="rounded-circle img-fluid" width="150">
            {% else %}
                <p>Pas d'image de profil</p>
            {% endif %}
            <form method="POST" enctype="multipart/form-data" class="w-100 mt-3">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ p_form.profile_image.id_for_label }}"></label>
                    <label class="btn btn-secondary">
                        Choisir un fichier <input type="file" id="{{ p_form.profile_image.id_for_label }}" name="{{ p_form.profile_image.html_name }}" accept="image/*" class="form-control-file" style="display: none;">
                    </label>
                </div>
                <button type="submit" class="btn btn-primary mt-2">Mettre à jour</button>
            </form>
            <a href="{% url 'users:delete_account' %}" class="btn btn-danger mt-3">Supprimer mon compte</a>
        </div>
    </div>
</section>
<section class="h-25">
    <div class="container">
        <div class="row justify-content-center mt-5">
            <h2>{{ user.email }}</h2>
        </div>
    </div>
</section>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Créer un compte{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<section id="harasai">
    <div class="container">
        <div class="row justify-content-center">
            <h2 class="bg-secondary p-2 rounded text-light mb-5">Créer un compte</h2>
        </div>
        <div class="row justify-content-center">
            <form method="post" class="bg-light p-3 rounded">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="form-group">
                    <label for="id_gender">Genre :</label>
                    <select id="id_gender" name="gender" class="form-control">
                        <option value="M">Male</option>
                        <option value="F">Female</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Créer un compte</button>
                <p class="mt-3">Vous avez déjà un compte? <a href="{% url 'users:login' %}">Se connecter</a></p>
            </form>
        </div>
    </div>
</section>
{% endblock %}